# Generated by Django 6.0.4 on 2026-05-09 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('dado_vida', models.IntegerField()),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('bono_fuerza', models.IntegerField(default=0)),
                ('bono_destreza', models.IntegerField(default=0)),
                ('bono_constitucion', models.IntegerField(default=0)),
                ('bono_inteligencia', models.IntegerField(default=0)),
                ('bono_sabiduria', models.IntegerField(default=0)),
                ('bono_carisma', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'raza',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('vida_actual', models.IntegerField(default=10)),
                ('vida_maxima', models.IntegerField(default=10)),
                ('fuerza', models.IntegerField(default=10)),
                ('destreza', models.IntegerField(default=10)),
                ('constitucion', models.IntegerField(default=10)),
                ('inteligencia', models.IntegerField(default=10)),
                ('sabiduria', models.IntegerField(default=10)),
                ('carisma', models.IntegerField(default=10)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_personajes.clase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_personajes.raza')),
            ],
            options={
                'db_table': 'personaje',
            },
        ),
        migrations.CreateModel(
            name='PersonajeHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personajes.habilidad')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personajes.personaje')),
            ],
            options={
                'db_table': 'personaje_habilidad',
                'unique_together': {('personaje', 'habilidad')},
            },
        ),
    ]
